# Originally based on the scratchfoundation/paper.js deploy.yml, but
# without the deployment steps and since has been modified more.

name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: -Xmx3200m
      JDK_JAVA_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED
    steps: 
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup submodule
        run: git submodule update --init --recursive
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config libcairo2-dev libpango1.0-dev libssl-dev libjpeg62-dev libgif-dev
          npm set progress=false
          which gulp || npm install -g gulp-cli    
      - name: Install NPM Dependencies
        run: npm ci
      - run: gulp jshint
      - run: gulp minify
      - run: gulp test
      - run: gulp zip
